# Generated by Django 5.0.6 on 2024-05-22 16:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='customers',
        ),
        migrations.RemoveField(
            model_name='route',
            name='total_distance',
        ),
        migrations.RemoveField(
            model_name='route',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='route',
            name='algorithm',
            field=models.CharField(default='ILP', max_length=20),
        ),
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='dataset',
            field=models.FileField(default='', upload_to='datasets/'),
        ),
        migrations.AddField(
            model_name='route',
            name='num_vehicles',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle_capacity',
            field=models.IntegerField(default=100),
        ),
    ]
