# Generated by Django 5.0.6 on 2024-05-22 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0003_route_distances_per_vehicle_route_route_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='depot_location',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='route',
            name='routes',
            field=models.JSONField(default=dict),
        ),
    ]
