# Generated by Django 5.0.6 on 2024-05-23 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0004_route_depot_location_route_routes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='depot_location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distances_per_vehicle',
        ),
        migrations.RemoveField(
            model_name='route',
            name='route_result',
        ),
        migrations.RemoveField(
            model_name='route',
            name='routes',
        ),
        migrations.RemoveField(
            model_name='route',
            name='total_distance',
        ),
        migrations.AlterField(
            model_name='route',
            name='algorithm',
            field=models.CharField(default='ILP', max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle_capacity',
            field=models.IntegerField(default=100),
        ),
    ]
