# Generated by Django 5.0.6 on 2024-05-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routing', '0005_remove_route_depot_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='depot_location',
            field=models.TextField(default='(0.0, 0.0)'),
        ),
        migrations.AddField(
            model_name='route',
            name='distances_per_vehicle',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='route',
            name='routes',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='route',
            name='total_distance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='route',
            name='algorithm',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='route',
            name='dataset',
            field=models.FileField(upload_to='datasets/'),
        ),
        migrations.AlterField(
            model_name='route',
            name='num_vehicles',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='route',
            name='vehicle_capacity',
            field=models.IntegerField(),
        ),
    ]
